### ISSUE TITLE
Dist possibly broken by Mojolicious v9 changes

### ISSUE THREAD

**Issue by leejo** [jberger/Mojo-SAML#9]
As per: https://github.com/mojolicious/mojo/wiki/Upgrading

lib code and/or tests in this distribution appears to use one or more of: via, over, detour, route

It's likely this dist will no longer work with Mojolicious v9 - check the aforementioned link for upgrade details.

Thanks!
Lee.

**Comment by jberger** [comment]
Thanks but this is a false-positive. I have a plugin attribute named route which is being set with its accessor method. Cheers!
